<a href="https://colab.research.google.com/github/halimaturrohmah-hub/Halimatur-Rohmah/blob/main/2_RNN_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

print('Tensorflow: {}'.format(tf.__version__))

plt.rcParams['figure.figsize'] = (16, 10)
plt.rc('font', size=15)

Tensorflow: 2.20.0


Simple RNN Cell

In [2]:
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

In [3]:
X_data = np.array([[h]], dtype=np.float32)
X_data.shape

(1, 1, 4)

In [4]:
hidden_size = 2
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[ 0.2809856  -0.07489459]]], shape: (1, 1, 2)
states: [[ 0.2809856  -0.07489459]], shape: (1, 2)


In [5]:
rnn_2 = tf.keras.layers.SimpleRNN(units=hidden_size, return_sequences=True, return_state=True)
outputs, states = rnn_2(X_data)

print("X_data: {}, shape: {}".format(X_data, X_data.shape))
print("output: {}, shape: {}".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]]], shape: (1, 1, 4)
output: [[[-0.618979    0.13459736]]], shape: (1, 1, 2)
states: [[-0.618979    0.13459736]], shape: (1, 2)


Unfolding multiple sequences

In [6]:
X_data = np.array([[h, e, l, l, o]], dtype=np.float32)
X_data.shape

(1, 5, 4)

In [7]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]], shape: (1, 5, 4)

output: [[[ 0.6187202   0.5666092 ]
  [-0.02459417 -0.6564461 ]
  [ 0.44831973  0.10916162]
  [ 0.8665183   0.4151158 ]
  [ 0.82654357  0.51618886]]], shape: (1, 5, 2)

states: [[0.82654357 0.51618886]], shape: (1, 2)


Batching Input

In [8]:
X_data = np.array([[h, e, l, l, o],
                   [e, o, l, l, l],
                   [l, l, e, e, l]], dtype=np.float32)
X_data.shape

(3, 5, 4)

In [9]:
cell = tf.keras.layers.SimpleRNNCell(units=hidden_size)
rnn = tf.keras.layers.RNN(cell, return_sequences=True, return_state=True)
outputs, states = rnn(X_data)

print("X_data: {}, shape: {}\n".format(X_data, X_data.shape))
print("output: {}, shape: {}\n".format(outputs, outputs.shape))
print("states: {}, shape: {}".format(states, states.shape))

X_data: [[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]

 [[0. 1. 0. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]]], shape: (3, 5, 4)

output: [[[ 0.6468182   0.5739492 ]
  [-0.07409661 -0.81524014]
  [-0.2936027   0.69069195]
  [ 0.59460354 -0.29941756]
  [ 0.29609376 -0.5495172 ]]

 [[ 0.16638237 -0.30253908]
  [ 0.58242047 -0.36890727]
  [-0.55168927  0.12141282]
  [ 0.53726715  0.30083624]
  [-0.22237836 -0.3977585 ]]

 [[ 0.06850653  0.11906782]
  [ 0.07384439 -0.0176272 ]
  [ 0.09574955 -0.32451606]
  [-0.08561059 -0.08829092]
  [ 0.09383172  0.2354441 ]]], shape: (3, 5, 2)

states: [[ 0.29609376 -0.5495172 ]
 [-0.22237836 -0.3977585 ]
 [ 0.09383172  0.2354441 ]], shape: (3, 2)
